type ValidationFn<T = any> = (value: T, ...args: any[]) => boolean;
declare const isRequired: ValidationFn<string | number | any>;
declare const minLength: ValidationFn<string>;
declare const maxLength: ValidationFn<string>;
declare const exactLength: ValidationFn<string>;
declare const pattern: ValidationFn<string>;
declare const isEmail: ValidationFn<string>;
declare const isURL: ValidationFn<string>;
declare const isAlpha: ValidationFn<string>;
declare const isAlphaNumeric: ValidationFn<string>;
declare const isSlug: ValidationFn<string>;
declare const isLowercase: ValidationFn<string>;
declare const isUppercase: ValidationFn<string>;
declare const isMixedCase: ValidationFn<string>;
declare const isStrongPassword: ValidationFn<string>;
declare const isMediumPassword: ValidationFn<string>;
declare const isNumeric: ValidationFn<string | number>;
declare const isInteger: ValidationFn<number>;
declare const isFloat: ValidationFn<number>;
declare const isPositive: ValidationFn<number>;
declare const isNegative: ValidationFn<number>;
declare const minValue: ValidationFn<number>;
declare const maxValue: ValidationFn<number>;
declare const inRange: ValidationFn<number>;
declare const isValidDate: ValidationFn<string | Date>;
declare const minDate: ValidationFn<string | Date>;
declare const maxDate: ValidationFn<string | Date>;
declare const beforeDate: ValidationFn<string | Date>;
declare const afterDate: ValidationFn<string | Date>;
declare const isTime: ValidationFn<string>;
declare const isDateTime: ValidationFn<string>;
declare const isBoolean: ValidationFn<any>;
declare const minItems: ValidationFn<any[]>;
declare const maxItems: ValidationFn<any[]>;
declare const uniqueItems: ValidationFn<any[]>;
declare const itemType: ValidationFn<any[]>;
declare const hasRequiredKeys: ValidationFn<object>;
declare const keyType: ValidationFn<object>;
declare const hasExactKeys: ValidationFn<object>;
declare const isEmptyObject: ValidationFn<object>;
declare const isFileType: ValidationFn<string>;
declare const maxFileSize: ValidationFn<number>;
declare const minFileSize: ValidationFn<number>;
declare const isCreditCard: ValidationFn<string>;
declare const isUUID: ValidationFn<string>;
declare const isIPAddress: ValidationFn<string>;
declare const isMACAddress: ValidationFn<string>;
declare const isJSON: ValidationFn<string>;
declare const isHexadecimal: ValidationFn<string>;
declare const isBase64: ValidationFn<string>;

export { afterDate, beforeDate, exactLength, hasExactKeys, hasRequiredKeys, inRange, isAlpha, isAlphaNumeric, isBase64, isBoolean, isCreditCard, isDateTime, isEmail, isEmptyObject, isFileType, isFloat, isHexadecimal, isIPAddress, isInteger, isJSON, isLowercase, isMACAddress, isMediumPassword, isMixedCase, isNegative, isNumeric, isPositive, isRequired, isSlug, isStrongPassword, isTime, isURL, isUUID, isUppercase, isValidDate, itemType, keyType, maxDate, maxFileSize, maxItems, maxLength, maxValue, minDate, minFileSize, minItems, minLength, minValue, pattern, uniqueItems };
